Correct galera 10.2
sous-chefs/mariadb pull request #197
Opened 2018-04-19 16:25 UTC by sinfomicien

- It adds the mariabackup SST method support (#192)
- It installs correctly with preseed
- I tested with MariaDB 10.2
- Need another PR to be fully tested (#195), otherwise it will failed because dirmngr is missing and the key is not the good one.

2018-05-15 13:43 UTC, damacus requested changes

2018-05-15 13:43 UTC, damacus commented on metadata.rb
> +version '1.5.4'
Can we roll this change back? I'd like to get some testing improvements in first.

2018-05-15 13:43 UTC, damacus commented on recipes/_debian_galera.rb
> +preseed_file = '/var/cache/local/preseeding/mariadb-galera-server.seed'
I'd prefer a if/else block here. As it's clearer, rather than overriding the value

2018-05-22 15:50 UTC, sinfomicien commented
@damacus , i changed my code according to your review. Then rebase and squash everything. Does it seem ok for you now ?

2018-05-22 21:37 UTC, damacus approved these changes

2018-05-22 21:38 UTC, damacus approved these changes

2018-05-22 21:38 UTC, merged

2018-05-22 21:38 UTC, damacus commented
Thanks! 
Nice one.