Add flexibility for installables
sous-chefs/mariadb pull request #288
Opened 2019-12-30 17:44 UTC by bish0polis

## Description

In a world where the same binaries are provided by different installable artifacts, this tiny patch allows someone to specify the name of said binary delivery wrapper.

### Check List
- [ ] All tests pass. See https://github.com/sous-chefs/mariadb/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

2019-12-30 17:44 UTC, kitchen-porter commented
<!--
  0 Errors
  1 Warning: This Pull Request is probably ...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-02-20 20:59 UTC, xorima requested changes

2020-02-20 20:59 UTC, Xorima commented on resources/client_install.rb
> +  node.run_state['mariadb']['client_pkg'] = new_resource.package_name
Hey,

Why are we storing this inside the `run_state`?

2020-02-20 21:04 UTC, xorima requested changes

2020-02-20 21:04 UTC, Xorima commented on resources/server_install.rb
> +property :package_name,      String,        default: node['platform_family'] == 'debian' ? "mariadb-server-#{new_resource.version}" : 'MariaDB-server'
Inside the property definition there is no variable called `new_resource` only the raw property names as variables, so this should be: 
```suggestion
property :package_name,      String,        default: node['platform_family'] == 'debian' ? "mariadb-server-#{version}" : 'MariaDB-server'
```

2020-02-21 13:08 UTC, xorima requested changes

2020-02-21 13:08 UTC, Xorima commented on CHANGELOG.md
> +## [3.1.1] (2019-11-16)
```suggestion
## Unreleased
```

2020-02-21 13:09 UTC, Xorima commented
Hey @bish0polis 

Can you just check the tests related to this change and make sure they work locally, I know we have a few issues here with tests so want to ensure things are working

If you need a hand drop by the #sous-chefs channel in https://community-slack.chef.io/

Thanks

2020-03-11 08:54 UTC, Xorima commented
Hey @bish0polis 

Do you have time to work on this? It would be great to have in the code 

Thanks

Sous Chefs

2020-05-14 17:06 UTC, damacus commented
## Closing due to inactivity. 

If this is still an issue please reopen or open another PR. 

Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs

2020-05-14 17:06 UTC, closed without merging

2020-05-18 21:39 UTC, bish0polis commented
Sorry for the delay. I'll reopen this later, but I'll only be testing on cinc because of license issues.