Set and allow root password authentication on MariaDB 10.4+ #256
sous-chefs/mariadb pull request #336
Opened 2021-10-28 09:15 UTC by stissot

# Description

Describe what this change achieves

Since MariaDB 10.4, the Ubuntu/Debian packages configure the root@localhost account with only the `unix_socket` authentication plugin. When setting the root password, we must also activate the `mysql_native_password` plugin, otherwise the password is not set and a warning is issued instead:

```
ERROR: 1356  View 'mysql.user' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them
```

This fix the content of the `/var/lib/mysql/recovery.conf ` file to properly set the password

## Issues Resolved

#256 

## Check List

- [x] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

2021-10-28 22:32 UTC, stissot commented
When working on this, I realized the cookbook is only testing with MariaDB 10.3. So since this patch affects the compatibility with the server install using MariaDB 10.4+, I've added a Kitchen test suite for 10.4 while still testing with 10.3. And made easier to change the version globally once maintainers decide it's time to test by default with a newer version.

2021-10-28 22:56 UTC, ramereth requested changes

2021-10-28 22:56 UTC, ramereth commented on resources/server_install.rb
> +  set_password_command += if new_resource.version =~ /^10\.[0-3]/
This would be better I think.
```suggestion
  set_password_command += if new_resource.version.to_f <= 10.3
```

2021-10-29 09:43 UTC, stissot commented on resources/server_install.rb
> +  set_password_command += if new_resource.version =~ /^10\.[0-3]/
Thanks for the suggestion, I have fixed the version comparison method

2021-10-29 15:55 UTC, ramereth approved these changes

2021-10-29 15:55 UTC, merged

2021-10-29 15:55 UTC, kitchen-porter commented
Released as: [5.2.0](https://github.com/sous-chefs/mariadb/releases/tag/5.2.0)