Patch the ability to use a distro's own repo for the MariaDB package
sous-chefs/mariadb pull request #355
Opened 2023-03-10 23:17 UTC by sectopodwreck

# Description

There were converge issues when attempting to use either `mariadb_server_install` or `mariadb_client_install` with `setup_repo` set to `false`, allowing to use the distro's stock package repository. 

For Debian-based systems, it was still utilizing the `version` property, with the default value leading to an inconsistency to the current available package on debian's repo.

For RHEL-based systems, there was a naming issue where the client package is called `MariaDB-client` on MariaDB's own repository, but it's called `mariadb` on the RHEL repos. Another issue found was the case sensitivity of the package manager. While MariaDB's repo uses the convention `MariaDB-server`, stock RHEL uses `mariadb-server`.

## Issues Resolved

- Patched Debian based system's usage of the `version`. (The addition of using version alongside the stock repo wasn't considered, as there is usually only one version available at a time, each distro having a different version)
- Patched the ability to install the stock MariaDB client and server on DNF-based systems.

## Issues Witnessed

The original `server_install.rb` integration tests checks to see if  the `mysql` service exists. `amazonlinux-7`, `centos-7`, and `ubuntu-1804`'s stock packages do not create the `mysql` service. The `mariadb` service exists, however.

## Check List

- [ ] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

2023-03-11 01:02 UTC, ramereth requested changes
Please update `.github/workflows/ci.yml` so that the two new suites will be included in the CI run.

2023-03-11 01:02 UTC, ramereth commented on CHANGELOG.md
> +## 5.2.10 - *2023-03-02*
Do not add a release, our automated process will do this once it gets merged.

2023-03-11 01:02 UTC, ramereth commented on resources/client_install.rb
> +
This is not needed, please remove.

2023-03-13 22:07 UTC, sectopodwreck commented
I still have an issue that needs to be patched. And I think I might have deleted the CHANGELOG file in my previous commit.

2023-03-14 05:40 UTC, ramereth commented
@sectopodwreck it doesn't look like you rebased from the `origin/main` branch. Can you please do that?

2023-04-05 09:41 UTC, damacus commented
Can you, undelete the CHANGELOG please

2023-04-06 21:20 UTC, sectopodwreck commented
There seems to be an issue in the converging of some Debian-based systems where `apply-mariadb-root-password` is not idempotent, even though the password is correctly set on the first pass through. I am unsure as to why the guard isn't working.

2023-04-07 21:27 UTC, sectopodwreck commented
There is an issue with the Amazon distro servers right now, we might need to have to re-test sometime in the future.

Other than that, I am unable to add a label onto this project, if anyone else can please add an appropriate one, that can help with one of the failing tests.

With that, this PR should now help with ensuring that the `mariadb_server_install` resource will work perfectly, by default, when the developer sets `setup_repo` to `false`.

2023-04-11 08:07 UTC, damacus approved these changes

2023-04-11 08:08 UTC, merged

2023-04-11 08:08 UTC, kitchen-porter commented
Released as: [5.2.16](https://github.com/sous-chefs/mariadb/releases/tag/5.2.16)